# Generated by Django 5.2.1 on 2025-06-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_staffprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='notes',
            new_name='instructions',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='medicine',
            new_name='medication_name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('SUGGESTED', 'Suggested by Doctor'), ('PRESCRIBED', 'Prescribed by Pharmacist'), ('SCHEDULED', 'Scheduled for Patient')], default='SUGGESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
